{
 "title": "Mastodon Puma Stats",
 "description": "An HTTP request monitoring dashboard for Mastodon 4.4's Prometheus exporter",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "ruby_sidekiq_process_concurrency"
    }
   },
   { "name": "controller", "label": "Endpoint", "query": { "query": "ruby_http_requests_total" } },
   {
    "name": "cache_operation",
    "label": "Cache Operation",
    "query": {
     "query": "ruby_http_request_duration_seconds"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "HTTP Request Details ($instance)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "instance"
  },
  {
   "title": "Total Req/s",
   "type": "stat",
   "gridPos": { "h": 9, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(instance) (rate(ruby_http_requests_total{instance=~\"$instance\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "HTTP reqs per second ($controller)",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 21, "x": 3, "y": 1 },
   "targets": [
    {
     "expr": "sum by(controller) (rate(ruby_http_requests_total{instance=~\"$instance\", controller=~\"$controller\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Request Latency Graph ($instance)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "repeat": "instance"
  },
  {
   "title": "Time spent in HTTP request ($controller)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(controller) (rate(ruby_http_request_duration_seconds_sum{instance=~\"$instance\", controller=~\"$controller\"}[5m])) / sum by(controller) (rate(ruby_http_request_duration_seconds_count{instance=~\"$instance\", controller=~\"$controller\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time spent in SQL ($controller)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(controller) (rate(ruby_http_request_sql_duration_seconds_sum{instance=~\"$instance\", controller=~\"$controller\"}[5m])) / sum by(controller) (rate(ruby_http_request_sql_duration_seconds_count{instance=~\"$instance\", controller=~\"$controller\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Time spent in Redis ($controller)",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 45 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(controller) (rate(ruby_http_request_redis_duration_seconds_sum{instance=~\"$instance\", controller=~\"$controller\"}[5m])) / sum by(controller) (rate(ruby_http_request_redis_duration_seconds_count{instance=~\"$instance\", controller=~\"$controller\"}[5m]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cache Details ($instance, $cache_operation)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 96 },
   "repeat": "instance"
  },
  {
   "title": "99th ptile latency",
   "type": "gauge",
   "description": "The 99th percentile latency over cache operations that are not hits as seen by the client.",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(action) (ruby_http_request_redis_duration_seconds{quantile=\"0.9\", instance=~\"$instance\"}) > 0",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "90th ptile latency",
   "type": "gauge",
   "description": "The 90th percentile latency over cache operations that are not hits as seen by the client.",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 97 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by(action) (ruby_http_request_redis_duration_seconds{quantile=\"0.9\", instance=~\"$instance\"}) > 0",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}