{
 "title": "Mastodon Sidekiq Stats",
 "description": "A Sidekiq job monitoring dashboard for Mastodon 4.4's Prometheus exporter",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "instance",
    "label": "Instance",
    "query": {
     "query": "ruby_sidekiq_process_concurrency"
    }
   },
   { "name": "sidekiq_worker", "label": "Sidekiq Worker", "query": { "query": "ruby_sidekiq_jobs_total" } },
   {
    "name": "sidekiq_queue",
    "query": {
     "query": "ruby_sidekiq_process_concurrency"
    }
   }
  ]
 },
 "panels": [
  { "title": "Sidekiq Overview ($instance)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "instance" },
  {
   "title": "Processed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ruby_sidekiq_stats_processed{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Failed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ruby_sidekiq_stats_failed{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Busy",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ruby_sidekiq_stats_workers_size{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(hostname) (ruby_sidekiq_process_concurrency{instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Enqueued",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ruby_sidekiq_stats_enqueued{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Retries",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ruby_sidekiq_stats_retry_size{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Scheduled",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 15, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ruby_sidekiq_stats_scheduled_size{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Dead",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 18, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ruby_sidekiq_stats_dead_size{instance=~\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Database Connections",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(hostname) (ruby_active_record_connection_pool_connections{instance=~\"$instance\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(hostname) (ruby_active_record_connection_pool_size{instance=~\"$instance\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Busy ($sidekiq_queue)",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 5 },
   "repeat": "sidekiq_queue",
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(queues) (ruby_sidekiq_process_busy{instance=~\"$instance\", queues=~\"$sidekiq_queue\"})",
     "legendFormat": "__auto"
    },
    {
     "expr": "sum by(__name__) (ruby_sidekiq_process_concurrency{instance=~\"$instance\", queues=~\"$sidekiq_queue\"})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sidekiq Details ($instance, $sidekiq_worker)",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "repeat": "instance"
  },
  {
   "title": "Sidekiq Queue Delay timeline",
   "type": "state-timeline",
   "description": "A historical graph of the average queue delay for each of the main queues in Sidekiq. If the queues do not have wait-time, they are depicted green. They will go through yellow, orange and become red once the queue is backing up and worker jobs have to wait before being scheduled.",
   "gridPos": { "h": 5, "w": 16, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sort(sum by(queue) (ruby_sidekiq_queue_latency_seconds{instance=~\"$instance\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sidekiq Latency",
   "type": "stat",
   "description": "The running average latency of HTTP Queries that Mastodon is serving.",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by(job) (rate(ruby_sidekiq_job_duration_seconds_sum{instance=~\"$instance\"}[$__rate_interval])) / sum by(job) (rate(ruby_sidekiq_job_duration_seconds_count{instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sidekiq Jobs/sec",
   "type": "stat",
   "description": "The total amount of worker jobs that Sidekiq is performing.",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort(sum by(job) (rate(ruby_sidekiq_jobs_total{instance=~\"$instance\"}[$__rate_interval])))",
     "legendFormat": "total"
    },
    {
     "expr": "sort(sum by (job)(rate(ruby_sidekiq_failed_jobs_total{instance=~\"$instance\"}[$__rate_interval])))",
     "legendFormat": "failure"
    }
   ]
  },
  {
   "title": "Sidekiq Worker ($sidekiq_worker)",
   "type": "timeseries",
   "description": "Rate of sidekiq worker invocations by worker type, split out by success and failure.",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 36 },
   "targets": [
    {
     "expr": "sum by(job_name) (rate(ruby_sidekiq_jobs_total{job_name=~\"$sidekiq_worker\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{job_name}} Success"
    },
    {
     "expr": "sum by(job_name) (rate(ruby_sidekiq_failed_jobs_total{job_name=~\"$sidekiq_worker\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "{{job_name}} Failure"
    }
   ]
  },
  {
   "title": "Sidekiq Queue Delay",
   "type": "stat",
   "description": "The total amount of worker jobs that Sidekiq is performing.",
   "gridPos": { "h": 11, "w": 4, "x": 12, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort(sum by(queue) (ruby_sidekiq_queue_backlog{instance=~\"$instance\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "50,90,99th ptile latency ($sidekiq_worker)",
   "type": "gauge",
   "description": "The median, 90th and 99th percentile latency over Sidekiq worker invocations.",
   "gridPos": { "h": 6, "w": 8, "x": 16, "y": 36 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (quantile)(ruby_sidekiq_job_duration_seconds{quantile=\"0.5\",job_name=~\"$sidekiq_worker\", instance=~\"$instance\"}>0)",
     "legendFormat": "median"
    },
    {
     "expr": "avg by (quantile)(ruby_sidekiq_job_duration_seconds{quantile=\"0.9\",job_name=~\"$sidekiq_worker\", instance=~\"$instance\"}>0)",
     "legendFormat": "90th ptile"
    },
    {
     "expr": "avg by (quantile)(ruby_sidekiq_job_duration_seconds{quantile=\"0.99\",job_name=~\"$sidekiq_worker\", instance=~\"$instance\"}>0)",
     "legendFormat": "99th ptile"
    }
   ]
  },
  {
   "title": "Sidekiq Queue Depth",
   "type": "bargauge",
   "description": "A total number of worker jobs waiting in the queue, usually due to there not being enough worker threads or sidekiq jobs to handle them in time. This graph here shows the n-count of elements in the queue.",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 42 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sort(sum by(queue) (ruby_sidekiq_stats_enqueued{instance=~\"$instance\"}))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Sidekiq Latency ($sidekiq_worker)",
   "type": "timeseries",
   "description": "Running latency of sidekiq worker invocations by worker type.",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum by(job_name) (rate(ruby_sidekiq_job_duration_seconds_sum{job_name=~\"$sidekiq_worker\", instance=~\"$instance\"}[$__rate_interval])) / sum by(job_name) (rate(ruby_sidekiq_job_duration_seconds_count{job_name=~\"$sidekiq_worker\", instance=~\"$instance\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}